version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      RAILS_ENV: test
      RAILS_SERVE_STATIC_FILES: true
      RAILS_LOG_TO_STDOUT: true
      SECRET_KEY_BASE: 74b4f8658db4cc359c4f6d8401d043e91f449e10c18c958b1162b12e78fa6395c2860ca4b5da7b83228103a12042259b1d6ab9d67d938a3946a17000133ba239
    volumes:
      - ./tmp/db:/app/db  # Mount a volume for SQLite database file
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: http://backend:8080  # Use backend service name
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  db_data:  # Remove PostgreSQL volume if not needed
