version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: true
      RAILS_LOG_TO_STDOUT: true
      SECRET_KEY_BASE: 74b4f8658db4cc359c4f6d8401d043e91f449e10c18c958b1162b12e78fa6395c2860ca4b5da7b83228103a12042259b1d6ab9d67d938a3946a17000133ba239
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - backend

  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_database_user
      POSTGRES_PASSWORD: your_database_password

volumes:
  db_data:
